Adding Europe's Flag
rapidpro/ureport pull request #1072
Opened 2022-06-02 14:47 UTC by brunocavalcantelima

We request the addition of the flag of Europe, Here's the example:

![bandeira](https://user-images.githubusercontent.com/88914508/171656410-1d5191e6-b218-4261-b8c0-d186c418d402.png)

2022-06-06 09:25 UTC, norkans7 commented
@brunocavalcantelima you need to add favico file as well,
Check #1073

2022-06-06 09:26 UTC, norkans7 requested changes
favico missing

2022-06-06 13:46 UTC, brunocavalcantelima commented
> @brunocavalcantelima you need to add favico file as well, Check #1073



> @brunocavalcantelima you need to add favico file as well, Check #1073

Add favico

2022-06-06 14:01 UTC, norkans7 commented on ureport/settings_common.py
> +        flag="flag_europe.png",
use `flag_europe-uk.png` for consistency with the subdomain

2022-06-06 19:11 UTC, brunocavalcantelima commented on ureport/settings_common.py
> +        countries_codes=["EUR"],
I made the suggested updates.

2022-06-07 09:09 UTC, norkans7 approved these changes

2022-06-07 09:09 UTC, merged