Add OECS Flag
rapidpro/ureport pull request #644
Opened 2020-11-04 13:41 UTC by matmsa27

2020-11-06 14:30 UTC, norkans7 commented on ureport/settings_common.py
> +        count_link="http://oecs.ureport.in/count/",
To be accurate on the count of countries we changed to add the `countries_codes` as a list of countries alpha 3 ISO codes. See https://github.com/rapidpro/ureport/pull/645/files

We will deduplicate then to count the number of countries accurately

For this site I think it is not yet ready to be shown as we do not yet have a opinion to display

2020-11-06 14:32 UTC, norkans7 requested changes
Remove `static/img/flags/flag_oecs.png` too as that directory if no longer used

2021-06-21 20:38 UTC, matmsa27 commented
Hi @norkans7 , we adjusted the flag from OECS.

2021-06-21 20:43 UTC, norkans7 commented
screenshot?

2021-06-21 20:45 UTC, norkans7 commented on ureport/settings_common.py
> +        countries_codes=["ATG"],  # ["ATG", "VGB", "DMA", "GRD", "MSR", "KNA", "LCA", "VCT", "TCA"],
is ATG the only country here?
Why do you keep the comment of the others?

2021-06-21 21:23 UTC, matmsa27 commented on ureport/settings_common.py
> +        countries_codes=["ATG"],  # ["ATG", "VGB", "DMA", "GRD", "MSR", "KNA", "LCA", "VCT", "TCA"],
OECS is a workspace that works with many countries. We setup the ATG and keep the others to keep on code the information that OECS is a workspace that work with other countries, like [Pacific](https://github.com/rapidpro/ureport/blob/main/ureport/settings_common.py#L1408)

2021-06-21 21:24 UTC, matmsa27 commented
> screenshot?

![Clipboard - 21 de Junho de 2021 às 15_33](https://user-images.githubusercontent.com/10725273/122829862-e8201280-d2bd-11eb-8541-5c0b238d6784.png)

2021-06-22 15:26 UTC, merged