Added modifications to polls and stories API
rapidpro/ureport pull request #851
Opened 2022-01-03 13:31 UTC by alviriseup

Added modifications to polls and stories API call to solve the following two issues: #850 and #835

2022-01-04 17:37 UTC, norkans7 commented on ureport/api/serializers.py
> +        str_exclude_fields = request.GET.get('fields', '') if request else None
Are not the logic inverted with the parameters used?

2022-01-04 17:38 UTC, norkans7 requested changes
Add tests

2022-01-09 13:36 UTC, alviriseup commented on ureport/api/serializers.py
> +        str_exclude_fields = request.GET.get('fields', '') if request else None
You are correct. The naming convention was reversed; it is now fixed.

2022-01-11 10:04 UTC, norkans7 commented on ureport/api/tests.py
> +        poll = [self.second_featured_poll, self.first_featured_poll, self.another_poll, self.reg_poll]
variable name `polls` instead of poll as it is a list

2022-01-11 10:07 UTC, norkans7 commented on ureport/api/serializers.py
> +            print('exclude_allowed :',exclude_allowed)
remove the print statement

2022-01-11 13:07 UTC, alviriseup commented on ureport/api/tests.py
> +        poll = [self.second_featured_poll, self.first_featured_poll, self.another_poll, self.reg_poll]
variable name has been changed from poll to `polls`

2022-01-11 13:09 UTC, alviriseup commented on ureport/api/serializers.py
> +            print('exclude_allowed :',exclude_allowed)
the print statement has been removed.

2022-01-11 13:22 UTC, norkans7 requested changes
Make sure to run  the script `./code_check.py`

2022-01-12 08:05 UTC, norkans7 approved these changes
Thanks Alvi

2022-01-12 08:05 UTC, merged